version: '3.8'

services:
  whatsapp-api-dev:
    image: golang:1.24.3-alpine
    container_name: whatsapp-api-dev
    working_dir: /app
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
      - whatsapp-sessions-dev:/app/sessions
      - whatsapp-data-dev:/app/data
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - API_KEY=${API_KEY:-your-dev-api-key}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - DB_PATH=/app/data/whatsapp.db
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@localhost:5672/}
      - GIN_MODE=debug
    command: >
      sh -c "apk add --no-cache gcc musl-dev && 
             go install github.com/cosmtrek/air@latest && 
             air -c .air.toml"
    networks:
      - whatsapp-network-dev

networks:
  whatsapp-network-dev:
    driver: bridge

volumes:
  go-modules:
    driver: local
  whatsapp-sessions-dev:
    driver: local
  whatsapp-data-dev:
    driver: local
