version: '3.8'

services:
  whatsapp-api-dev:
    image: golang:1.24.3-alpine
    container_name: whatsapp-api-dev
    working_dir: /app
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
      - whatsapp-sessions-dev:/app/sessions
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - API_KEY=${API_KEY:-your-secure-api-key}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - RABBITMQ_URL=
    command: >
      sh -c "apk add --no-cache gcc musl-dev && 
             go install github.com/cosmtrek/air@latest && 
             air -c .air.toml"
    networks:
      - whatsapp-network-dev

networks:
  whatsapp-network-dev:
    driver: bridge

volumes:
  go-modules:
    driver: local
  whatsapp-sessions-dev:
    driver: local
