# docker-compose.yml
version: '3.8'

services:
  whatsapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsapp-api:latest
    container_name: whatsapp-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - whatsapp-sessions:/app/sessions
      - whatsapp-data:/app/data
    environment:
      - PORT=8080
      - API_KEY=${API_KEY:-your-secure-api-key}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - DB_PATH=/app/data/whatsapp.db
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@localhost:5672/}
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge

volumes:
  whatsapp-sessions:
    driver: local
  whatsapp-data:
    driver: local
