version: '3.8'

services:
  whatsapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsapp-api:latest
    container_name: whatsapp-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - API_KEY=
      - ADMIN_API_KEY=hello
      - DB_PATH=/app/data/whatsapp.db # Corrigido para usar /app/data
      - RABBITMQ_ENABLED=true
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - WEBHOOK_URL=
      - PRINT_QR=true
      - GIN_MODE=release
    volumes:
      - whatsapp_data:/app/data
      - whatsapp_sessions:/app/sessions
    networks:
      - whatsapp-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-whatsapp
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - whatsapp-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  whatsapp-network:
    driver: bridge

volumes:
  whatsapp_data:
    driver: local
  whatsapp_sessions:
    driver: local
  rabbitmq_data:
    driver: local
