name: Deploy to Docker Hub on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 
      
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: ./Dockerfile.worker
          push: true
          tags: |
            soureiwaster/nexus-go:${{ github.ref_name }}
            soureiwaster/nexus-go:latest
          cache-from: type=registry,ref=soureiwaster/nexus-go:buildcache
          cache-to: type=registry,ref=soureiwaster/nexus-go:buildcache,mode=max